package com.etl.noadk.domain;

import com.google.gson.annotations.SerializedName;
import java.util.*;

/**
 * Represents field mapping from source to canonical model.
 * Generated by Navigator agent.
 */
public class FieldMapping {
    @SerializedName("source_field")
    private String sourceField;

    @SerializedName("target_field")
    private String targetField;

    @SerializedName("target_type")
    private String targetType;

    @SerializedName("confidence_score")
    private double confidenceScore;

    @SerializedName("transformation_rule")
    private String transformationRule;

    @SerializedName("enrichment_sources")
    private List<String> enrichmentSources;

    @SerializedName("validation_rules")
    private List<ValidationRule> validationRules;

    @SerializedName("rationale")
    private String rationale;

    @SerializedName("is_key_field")
    private boolean isKeyField;

    @SerializedName("suggested_standards")
    private Map<String, String> suggestedStandards;

    public FieldMapping() {
        this.enrichmentSources = new ArrayList<>();
        this.validationRules = new ArrayList<>();
        this.suggestedStandards = new HashMap<>();
        this.confidenceScore = 1.0;
    }

    public FieldMapping(String sourceField, String targetField, String targetType) {
        this();
        this.sourceField = sourceField;
        this.targetField = targetField;
        this.targetType = targetType;
    }

    public static class ValidationRule {
        @SerializedName("type")
        private String type;

        @SerializedName("condition")
        private String condition;

        @SerializedName("error_message")
        private String errorMessage;

        public ValidationRule(String type, String condition, String errorMessage) {
            this.type = type;
            this.condition = condition;
            this.errorMessage = errorMessage;
        }

        // Getters
        public String getType() { return type; }
        public String getCondition() { return condition; }
        public String getErrorMessage() { return errorMessage; }
    }

    // Getters and setters
    public String getSourceField() { return sourceField; }
    public void setSourceField(String sourceField) { this.sourceField = sourceField; }

    public String getTargetField() { return targetField; }
    public void setTargetField(String targetField) { this.targetField = targetField; }

    public String getTargetType() { return targetType; }
    public void setTargetType(String targetType) { this.targetType = targetType; }

    public double getConfidenceScore() { return confidenceScore; }
    public void setConfidenceScore(double confidenceScore) { this.confidenceScore = confidenceScore; }

    public String getTransformationRule() { return transformationRule; }
    public void setTransformationRule(String transformationRule) { this.transformationRule = transformationRule; }

    public List<String> getEnrichmentSources() { return enrichmentSources; }
    public void setEnrichmentSources(List<String> enrichmentSources) { this.enrichmentSources = enrichmentSources; }

    public List<ValidationRule> getValidationRules() { return validationRules; }
    public void setValidationRules(List<ValidationRule> validationRules) { this.validationRules = validationRules; }

    public String getRationale() { return rationale; }
    public void setRationale(String rationale) { this.rationale = rationale; }

    public boolean isKeyField() { return isKeyField; }
    public void setKeyField(boolean keyField) { isKeyField = keyField; }

    public Map<String, String> getSuggestedStandards() { return suggestedStandards; }
    public void setSuggestedStandards(Map<String, String> suggestedStandards) { this.suggestedStandards = suggestedStandards; }
}

