package com.etl.noadk.domain;

import com.google.gson.annotations.SerializedName;
import java.util.*;

/**
 * Represents the source schema contract with type inference and confidence scores.
 * Generated by Cartographer agent.
 */
public class SchemaContract {
    @SerializedName("schema_id")
    private String schemaId;

    @SerializedName("version")
    private String version;

    @SerializedName("timestamp")
    private long timestamp;

    @SerializedName("fingerprint")
    private String fingerprint;

    @SerializedName("fields")
    private List<FieldContract> fields;

    @SerializedName("sample_rows")
    private List<Map<String, Object>> sampleRows;

    @SerializedName("statistics")
    private Statistics statistics;

    public SchemaContract() {
        this.fields = new ArrayList<>();
        this.sampleRows = new ArrayList<>();
        this.statistics = new Statistics();
        this.timestamp = System.currentTimeMillis();
    }

    public static class FieldContract {
        @SerializedName("name")
        private String name;

        @SerializedName("inferred_type")
        private String inferredType;

        @SerializedName("confidence_score")
        private double confidenceScore;

        @SerializedName("null_percentage")
        private double nullPercentage;

        @SerializedName("sample_values")
        private List<Object> sampleValues;

        @SerializedName("is_unique")
        private boolean isUnique;

        @SerializedName("detected_patterns")
        private List<String> detectedPatterns;

        public FieldContract(String name, String inferredType) {
            this.name = name;
            this.inferredType = inferredType;
            this.confidenceScore = 1.0;
            this.sampleValues = new ArrayList<>();
            this.detectedPatterns = new ArrayList<>();
        }

        // Getters and setters
        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

        public String getInferredType() { return inferredType; }
        public void setInferredType(String inferredType) { this.inferredType = inferredType; }

        public double getConfidenceScore() { return confidenceScore; }
        public void setConfidenceScore(double confidenceScore) { this.confidenceScore = confidenceScore; }

        public double getNullPercentage() { return nullPercentage; }
        public void setNullPercentage(double nullPercentage) { this.nullPercentage = nullPercentage; }

        public List<Object> getSampleValues() { return sampleValues; }
        public void setSampleValues(List<Object> sampleValues) { this.sampleValues = sampleValues; }

        public boolean isUnique() { return isUnique; }
        public void setUnique(boolean unique) { isUnique = unique; }

        public List<String> getDetectedPatterns() { return detectedPatterns; }
        public void setDetectedPatterns(List<String> detectedPatterns) { this.detectedPatterns = detectedPatterns; }
    }

    public static class Statistics {
        @SerializedName("row_count")
        private long rowCount;

        @SerializedName("file_size_bytes")
        private long fileSizeBytes;

        @SerializedName("encoding")
        private String encoding;

        @SerializedName("delimiter")
        private String delimiter;

        public Statistics() {
            this.encoding = "UTF-8";
        }

        // Getters and setters
        public long getRowCount() { return rowCount; }
        public void setRowCount(long rowCount) { this.rowCount = rowCount; }

        public long getFileSizeBytes() { return fileSizeBytes; }
        public void setFileSizeBytes(long fileSizeBytes) { this.fileSizeBytes = fileSizeBytes; }

        public String getEncoding() { return encoding; }
        public void setEncoding(String encoding) { this.encoding = encoding; }

        public String getDelimiter() { return delimiter; }
        public void setDelimiter(String delimiter) { this.delimiter = delimiter; }
    }

    // Getters and setters
    public String getSchemaId() { return schemaId; }
    public void setSchemaId(String schemaId) { this.schemaId = schemaId; }

    public String getVersion() { return version; }
    public void setVersion(String version) { this.version = version; }

    public long getTimestamp() { return timestamp; }
    public void setTimestamp(long timestamp) { this.timestamp = timestamp; }

    public String getFingerprint() { return fingerprint; }
    public void setFingerprint(String fingerprint) { this.fingerprint = fingerprint; }

    public List<FieldContract> getFields() { return fields; }
    public void setFields(List<FieldContract> fields) { this.fields = fields; }

    public List<Map<String, Object>> getSampleRows() { return sampleRows; }
    public void setSampleRows(List<Map<String, Object>> sampleRows) { this.sampleRows = sampleRows; }

    public Statistics getStatistics() { return statistics; }
    public void setStatistics(Statistics statistics) { this.statistics = statistics; }
}

